language: rust
rust:
  - nightly
addons:
  apt:
    packages:
      - nasm
os:
  - linux
  - osx
before_install:
    - if [ `uname` = "Darwin" ]; then
        brew tap altkatz/homebrew-gcc_cross_compilers;
        brew update;
        brew install i386-elf-binutils nasm;
      fi
script:
  - make clean
  - make all

