[package]
name = "network"
version = "0.1.0"
authors = []

[dependencies]
common = {path = "../common"}
drivers = {path = "../drivers"}
programs = {path = "../programs"}
syscall = {path = "../syscall"}
